export const site = {
  name: 'SPRIN RUN 2027',
  description: '#SPRINRUN2027 #EveryStepSavesALife #SelamatkanPerempuanIndonesia #CharityRun #Pogi',
  url: process.env.NEXT_PUBLIC_SITE_URL ?? 'https://sprinrun2027.vercel.app',
  eventDate: 'Minggu, 17 Januari 2027',
  venue: 'Kantor Gubernur Jawa Tengah',
  routeStartMapUrl: 'https://www.google.com/maps/search/?api=1&query=-6.9931,110.4213',
  whatsappNumber: process.env.NEXT_PUBLIC_WHATSAPP_NUMBER ?? '6281227875478',
  contactName: 'dr. Radith Aulia, Sp.OG',
  contactPhone: '+62 812-2787-5478',
  whatsappMessage: 'Halo, saya ingin mengetahui lebih lanjut tentang SPRIN RUN 2027.',
  registrationUrl: '#registration',
  labels: {
    menu: 'Menu',
    skipLink: 'Lewati ke konten',
    heroTitle: 'Every Step. Saves a Life',
    heroAction: 'Info Pendaftaran',
    sectionTitle: 'Info Pendaftaran',
    sectionAction: 'Lihat Detail',
    notFoundTitle: 'Halaman Tidak Ditemukan',
    notFoundAction: 'Kembali ke Beranda',
  },
  navigation: [
    { label: 'Beranda', href: '#home' },
    { label: 'Kategori', href: '#race' },
    { label: 'Tentang', href: '#about' },
    { label: 'Race Kit', href: '#race-kit' },
    { label: 'Rute', href: '#route' },
    { label: 'Rundown', href: '#rundown' },
    { label: 'FAQ', href: '#faq' },
  ],
  primaryNavigation: [
    { label: 'Tentang', href: '#about' },
    { label: 'Kategori', href: '#race' },
    { label: 'Rute', href: '#route' },
    { label: 'Rundown', href: '#rundown' },
  ],
} as const;

export type SitePath = (typeof site.navigation)[number]['href'];
